### ISSUE TITLE
Error when running tensorrt baseline

### ISSUE THREAD

**Issue by Laurawly** [vinx13/tvm-cuda-benchmark#9]
Hi @vinx13 ,

When I run `run_tensorrt.py` I got the following error:
```
/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py:67: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
Traceback (most recent call last):
  File "run_tensorrt.py", line 33, in <module>
    main()
  File "run_tensorrt.py", line 25, in main
    prepare_onnx_model(model)
  File "run_tensorrt.py", line 18, in prepare_onnx_model
    mx.contrib.onnx.mx2onnx.export_model.export_model(sym, params=arg_param, input_shape=[shape[1] for shape in data_shape], onnx_file_path=path)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_model.py", line 87, in export_model
    verbose=verbose)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 312, in create_onnx_graph_proto
    checker.check_graph(graph)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 53, in checker
    proto.SerializeToString(), ctx)
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: spatial for operator BatchNormalization

==> Context: Bad node spec: input: "data" input: "bn_data_gamma" input: "bn_data_beta" input: "bn_data_moving_mean" input: "bn_data_moving_var" output: "bn_data" name: "bn_data" op_type: "BatchNormalization" attribute { name: "epsilon" f: 2e-05 type: FLOAT } attribute { name: "momentum" f: 0.9 type: FLOAT } attribute { name: "spatial" i: 0 type: INT }
```
The TensorRT version I'm using is 7.0. My mxnet version is 1.6.0. Onnx version is 1.6.0

**Comment by Laurawly** [comment]
Update on the issue: 
After I downgrade onnx from 1.6 to 1.3.0, the error disappears, but new error occurs as follows:
```
ERROR: ModelImporter.cpp:457 In function importModel:
[4] Assertion failed: !_importer_ctx.network()->hasImplicitBatchDimension() && "This version of the ONNX parser only supports TensorRT INetworkDefinitions with an explicit batch dimension. Please ensure the network was created using the EXPLICIT_BATCH NetworkDefinitionCreationFlag."
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
```

**Comment by vinx13** [comment]
This code was tested under TensorRT 5 and onnx (either 1.3 or 1.4, I don't remember exactly). Btw, as your error message implied, do you have explicit batch size in your onnx model file (i.e each layer has fixed batch size)?

**Comment by Laurawly** [comment]
It should be onnx 1.3, I tried 1.4 it didn't work. Also I used your original script. It turns out to be the problem with TRT 7.0. After downgrading it to 6.0, the error is gone. But I got a warning like this:
```
WARNING: Tensor (Unnamed Layer* 173) [Constant]_output is uniformly zero; network calibration failed.
```
Not sure if that's gonna affect the accuracy.

**Comment by vinx13** [comment]
The warning is likely related to the params. Since I was testing the performance, not the accuracy, I randomly initialized the weights, which may make calibration fail.

**Comment by Laurawly** [comment]
I see, thanks. Also do you know how to test only conv2d performance workload by workload from TensorRT?

**Comment by vinx13** [comment]
You can either use a TensorRT profiler (implementing `IProfiler`) or directly create a one-layer model

**Comment by Laurawly** [comment]
Cool, thanks!
